name: 'Multiple Repository Dispatch'
description: 'Trigger dependent repo builds using multiple repository_dispatch events'
author: '1Q1'
inputs: 
  repos:
    description: 'The repositories target.'
    required: true
  token:
    description: 'GitHub Personal Access Token'
    required: true
  user:
    description: 'GitHub username'
    required: true
  action:
    description: "Event action"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.user }}
    - ${{ inputs.token }}
    - ${{ inputs.action }}
    - ${{ inputs.repos }}